--- 
steps: 
  - 
    args: 
      - ['bash', 'apt-get install gcc g++ libssl-dev openssl libudev-dev pkg-config file make -y']
      - 'cargo check'
    name: "rust:latest"
  - 
    args: 
      - "apt-get install gcc g++ libssl-dev openssl libudev-dev pkg-config file make -y"
      - "cargo test --all --verbose"
    name: "rust:latest"
  - 
    args: 
      - "cargo build"
    name: "rust:latest"
		
